# Generated by Django 2.2 on 2020-04-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dojos', to='dojo_ninjas_app.Dojo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninja',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
